# -*- coding: utf-8 -*-
"""MDD_7_Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDGZJ9MA4-zxDrhAVhQEyPMulCGyRTs-

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-ensamble-clas.pkl'
model_rf, min_max_scaler,labelencoder, variables = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
# data = pd.read_csv("videojuegos-datosFuturos.csv")
# data.head()

#Aquí va la interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de rentabilidad o pérdida de financiación de Bills médicos')

#Captura de datos
AccountName = st.selectbox('Account Name', ["'Ace Law Group'", "'Angulo Law Group'",
       "'Atkinson Watkins & Hoffman Attorneys'", "'BD & J Law Firm'",
       "'Benjamin Nadig Law'", "'Benson Allred Injury Law'",
       "'Blackburn Wirth Injury Team'", "'Cardenas Law Group'",
       "'David W Fassett Personal Injury Law'", "'Dimopoulos Injury Law'",
       "'ER Injury Attorneys'", "'Fuller Law Practice'",
       "'G Dallas Horton & Associates'", "'Goldberg Injury Law'",
       "'Jacoby & Meyers CA'", "'Ladah Law'",
       "'Lalezary Law Firm CA Law Brothers'",
       "'Law Office of Arash Khorsandi'", "'Law Office of Stephen Reid'",
       "'Law Office of Victor M Cardoza'", "'Lawrence C Hill & Associates'",
       "'Lloyd Baker Injury Attorneys'", "'Mullins & Trenchak Law'",
       "'Muslusky Law'", "'Naqvi Injury Law'", "'Neal Hyman Law'",
       "'Nwogbe Law Group'", "'Parke Law Firm'", "'RRCC Firm'",
       "'Sidell Injury Law'", "'Valarie Fujii Law Offices'",
       "'Vannah & Vannah Law Firm'", "'VC2 Law'",
       "'Willoughby Shulman Injury Lawyers'", "'Wilshire Law Firm CA'",
       "'Yan Kenyon Law'"])
ProviderClient = st.selectbox('Provider Client', ["'Pueblo Medical Imaging'", "'LVR'",    "'Durango Surgery Center'",
       "'Parkway Surgery Center'", "'Suarez Physical Therapy'",
       "'Jackson Physical Therapy'", "'Simpson Chiropractic'",
       "'Precision Medical Products'", "'OpenSided MRI of Las Vegas'",
       "'Surgical Arts Centre'", "'LVC Surgery Center'"])
Subject = st.selectbox('Subject', ["'Lien'", "'Imaging'", "'Pain Management'", "'Physical Therapy'","'Chiropractic'", "'Medical Device'", "'Administrative'", "'Surgery'"])
PurchAmt = st.number_input('Purchase Amount')
BillAmt = st.number_input('Bill Amount')



#Dataframe
datos = [[AccountName, ProviderClient, Subject,PurchAmt,BillAmt]]
data = pd.DataFrame(datos, columns=['Account Name', 'Provider Client', 'Subject','Purch Amt','Bill Amt']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data, columns=['Account Name','Provider Client','Subject'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

"""# ***Predicciones***
**El modelo presenta un error del 12%**
"""

#Hacemos la predicción con el Tree
Y_pred = model_rf.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data